# Generated by Django 4.0.4 on 2022-04-16 21:47

from django.db import migrations, models
import review_my_courses.models


class Migration(migrations.Migration):

    dependencies = [
        ('review_my_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='year',
            field=models.PositiveIntegerField(default=2022, validators=[review_my_courses.models.validate_year]),
        ),
    ]
