# Generated by Django 4.0.4 on 2022-04-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_my_courses', '0003_alter_school_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('school_id', 'title', 'course_code'), name='unique_course'),
        ),
    ]
