# Generated by Django 4.0.4 on 2022-04-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_my_courses', '0005_remove_course_unique_course_course_unique_course'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('school', 'title', 'course_code')},
        ),
    ]
