# Generated by Django 4.0.4 on 2022-04-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_my_courses', '0006_remove_course_unique_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('school', 'title', 'course_code'), name='unique_course'),
        ),
    ]
