# Generated by Django 4.0.4 on 2022-04-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_my_courses', '0007_alter_course_unique_together_course_unique_course'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('title', 'course_code'), name='unique_course'),
        ),
    ]
